title: SSH 使用 Kerberos 认证
id: kerberos-ssh
date: 2015-09-18 14:32:00
tags:
- Kerberos
- SSH
- 运维
---

= SSH 使用 Kerberos 认证

== 背景

Kerberos 是一款第三方认证软件，提供专属的 Kerberos 认证协议。在集群环境下，对统一的认证管理非常有帮助。我们常见的 SSH 认证方式有用户名密码认证，公钥私钥认证等，这些认证比较适合个人使用，但如果管辖的机器过多，就会出现调整认证的不方便。譬如：有 100 台服务器，由于业务需要，这些机器需要做到对特定账号免登，如果使用公钥私钥的方式，需要在每台机器中都要放置一个公钥和私钥，如果有一天私钥泄漏了，想要将这 100 台机器的认证私钥都调整一遍，真不是一件容易的事情。而对于集中认证的 Kerberos 来说，却是非常容易，只需要在 Kerberos 服务端重置一下 KEY 即可。

== 目标

. 实现各个服务器之间的免登；
. 认证泄漏后，调整成本最小；

== 方案架构

根据实际情况和安全需要，本方案设计双层认证的机制：

.双层认证方案
. 开设 ansible 账号，为每台机器设置 ansible 账号的认证权限；
. ansible 的认证仅在跳板机上进行；
. 开设 communication 账号，为每台机器设置 communication 账号的认证权限；
. communication 的认证会在每一台服务器上进行，由 ansible 进行。

.安全措施
. 如果 ansible 认证泄漏，仅需要在 Kerberos 服务器上重置 ansible 账号的 KEY，在跳板机重新对 ansible 账号进行认证即可。
. 如果 communication 认证泄漏，需在 Kerberos 服务器上重置 communication 账号的 KEY，同时通过 ansible 账号对每台机器的 communication 账号进行认证。

.架构图
----
{% plantuml %}
node Jump as J
node Kerberos as K
node "Machine A" as A
node "Machine B" as B
node "Machine C" as C
node "Machine D" as D

J --> A : ansible
J --> B
J --> C
J --> D

A --> B : communication
A --> C
A --> D

A <-> K


{% endplantuml %}
----

== SSHD配置

.sshd_config
----
ChallengeResponseAuthentication no

KerberosAuthentication no
KerberosOrLocalPasswd no
KerberosTicketCleanup no

GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
GSSAPIStrictAcceptorCheck no
GSSAPIKeyExchange no

UsePAM yes
----

.整体参考
----
Protocol 2
SyslogFacility AUTHPRIV
LogLevel INFO
PermitRoot no
PasswordAuthentication yes
ChallengeResponseAuthentication no
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
UsePAM yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
X11Forwarding yes
Subsystem       sftp    /usr/libexec/openssh/sftp-server
----

== ssh server/client上Kerberos配置

=== krb5.conf

.krb5.conf
----
[logging]
 default = FILE:/var/log/krb5libs.log

[libdefaults]
 default_realm = 7V1.NET
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 7V1.NET = {
  kdc = 172.17.0.35
  admin_server = 172.17.0.35
  default_domain = 7v1.net
 }

[domain_realm]
 .7v1.net = 7V1.NET
 7v1.net = 7V1.NET
----

NOTE: 这里使用7v1.net作为例子。

=== 添加principal

在`Kerberos`中注册本机

.server
----
kadmin -q "ank -randkey host/ssh.7v1.net"
----

.client
----
kadmin -q "ank -randkey host/client.7v1.net"
----

=== 导出principal key

把本机的key的添加到keytab中

.server
----
kadmin -q "ktadd host/ssh.7v1.net"
----

.client
----
kadmin -q "ank -randkey host/client.7v1.net"
----

=== 在服务端配置.k5login文件

[title=.k5login]
----
username@7V1.NET
----

== Kerberos服务器配置调整

由于`Kerberos`版本升级兼容问题footnoteref:[note2,http://web.mit.edu/kerberos/krb5-devel/doc/admin/troubleshoot.html]，
krb5 1.7及以后版本禁用了`DES encryption key`，会导致错误
`credential verification failed: KDC has no support for encryption type`，
请参考下面解决

....
This most commonly happens when trying to use a principal with only DES keys, in a release (MIT krb5 1.7 or later) which disables DES by default. DES encryption is considered weak due to its inadequate key size. If you cannot migrate away from its use, you can re-enable DES by adding allow_weak_crypto = true to the [libdefaults] section of krb5.conf.
....

== Trouble shooting

=== “KDC has no support for encryption type”

krb5 1.7及以后版本禁用了`DES encryption key`所致。

=== “Wrong principal in request/debug1: Got no client credentials”

服务器没有配置 .k5login

=== “No key table entry found matching xxxxxx”

服务端没有把导出key到keytab
