title: 构建、打包、部署系统设计
id: build-package-deploy-system
date: 2015-11-20
----

= 构建、打包、部署系统设计

== 背景

任何项目都存在构建、打包和部署的需求。

== 场景

. 在指定 10 台机器上部署 A 项目的 B、C、D 服务。
. 上线 A 项目最新的代码并重启 B、C、D 服务。
. A 项目依赖了 E、F 项目，上线的时候需要同时部署 E、F 项目的代码。
. E 项目的代码更新了，需要上线。
. E 项目上线完成后，重启 A 项目的 B、C、D 服务。
. A 项目根据源代码对资源文件进行打包并发布。
. 需要在 CI 环境下运行 A 项目的 Test Case。
. A 项目部署或更新时，需要加载某些事先打好的资源文件。
. A 项目部署时，不需要部署源代码，只需要部署对应的二进制可执行文件及相关的配置文件。

== 概念

=== 项目（Project）

项目名称为无空格的英文单词或词组，以此为文件名，统一管理在上线系统中。

=== Git库（Git Repo）

一个项目对应着一个 Git 库，如果碰到项目非常复杂，需要拆分 Git 库，建议采用 git submodule 的方式来实现，而顶级 Git 库对应着一个项目。

项目对应着拉去Git库的最小单位，如果一个子模块是独立拉取代码，则它为一个独立的项目；
反之，它不能为一个独立的项目，它属于父级Git项目，它的服务也由父级项目提供部署设置。

=== 服务（Service）

服务是部署系统中所管辖的最小单位。服务隶属于某个项目，一个项目可能会包含多个服务，譬如：Gunicorn、Nginx、Thrift Service 等；项目也可能一个服务都没有，譬如公共库。

服务有一些操作动作，譬如：启动、重启、更新等。

=== 操作（Action）

对一个项目、服务可以有一些操作，譬如部署、重启、打包、测试等等。有的操作可能是本地的，有的操作可能是远程的；

=== 机器（Machine/Host）

机器是具有独立的 Host 地址，可以部署服务的实例，
包括真实的机器、虚拟机、Docker 容器等。

=== 组（Group）

按项目或服务对机器进行分组，譬如：

----
[bpm]
10.0.1.[2:100]
[bpm:test]
10.0.1.2
[bpm:gunicorn]
10.0.1.[3:50]
[bpm:thrift]
10.0.1.[51:100]
----

=== 补丁（Patchset）

补丁是指提交到 Gerrit Code Review 上的一个更改。
微观来看，一个补丁可以视为一个 Commit，只是一个 Commit 只对应一个 Patchset 的一个版本，所有在一次更改过程中，只会有一个 Commit 会被合并到主干（master）分支。

补丁是进行 CI 的最小单位。

=== 分支（Branch）

指 Git 的分支，本方案主要是使用三个分支：master，test，online。master 分支是主干分支，开发工作是围绕开发分支完成的。

=== 项目之间的依赖（Dependancy）

项目之间会存在一些依赖关系，譬如 A 为基础库，B 和 C 都会引用代码库 A 的代码。那么，部署项目 B 时，必须把项目 A 也一起部署到目标机器上。

=== 部署（Deploy）

部署有两层含义：

. 部署代码库或二机制包
. 部署服务

=== 预上线（PreRelease）

=== 上线（Release）

=== 持续集成（CI）

=== 构建（Build）

由源代码构建出二进制可执行文件、资源文件。

=== 打包（Package）

将构建出的二进制可执行文件或资源文件打成可分发的包。

=== 包发布（Package Deploy）

== 方案

=== 约定

. 项目由 Git 库的拉取方式决定，一个项目可能由多个 Git 库构成，如果是多 Git 库的情况，该 Git 库的组织方式必须是 submodule。
. 一个 Git 库只能属于一个项目。
. 部署、预上线、上线均由两部分构成，代码或二进制包和服务。

=== 持续集成（CI）

=== 部署（Deploy）

=== 流程

.部署（Deploy）
. 根据Host

.预发布
. 提交代码至`master`分支；
. 将`master`分支发布到`test分支`；

.上线

=== 存储
